import { createHash } from 'node:crypto';
import * as fs from 'node:fs';
import * as path from 'node:path';

/**
 * Logical contract name → `out/` artifact basename. Upstream Lido contracts are
 * compiled by the contracts repo as INTERFACES only, so they map to their
 * `I`-prefixed artifacts; module/suite contracts use their impl artifacts.
 */
export const CONTRACT_SOURCES = {
  // module + suite impls (out/<C>.sol/<C>.json)
  CSModule: 'CSModule',
  CuratedModule: 'CuratedModule',
  Accounting: 'Accounting',
  FeeDistributor: 'FeeDistributor',
  FeeOracle: 'FeeOracle',
  HashConsensus: 'HashConsensus',
  VettedGate: 'VettedGate',
  CuratedGate: 'CuratedGate',
  PermissionlessGate: 'PermissionlessGate',
  ParametersRegistry: 'ParametersRegistry',
  MetaRegistry: 'MetaRegistry',
  Verifier: 'Verifier',
  // upstream protocol interfaces (out/I<C>.sol/I<C>.json)
  VEBO: 'IVEBO',
  StakingRouter: 'IStakingRouter',
  Lido: 'ILido',
  LidoLocator: 'ILidoLocator',
} as const;

export type ContractName = keyof typeof CONTRACT_SOURCES;

export function readAbi(outDir: string, source: string): unknown[] {
  const p = path.join(outDir, `${source}.sol`, `${source}.json`);
  if (!fs.existsSync(p)) {
    throw new Error(
      `ABI artifact not found at ${p} (did you run \`forge build\` in the contracts repo?)`,
    );
  }
  const artifact = JSON.parse(fs.readFileSync(p, 'utf8')) as { abi?: unknown[] };
  if (!Array.isArray(artifact.abi)) {
    throw new Error(`No 'abi' array in ${p}`);
  }
  return artifact.abi;
}

export function extractAbis(outDir: string): Record<ContractName, unknown[]> {
  const out = {} as Record<ContractName, unknown[]>;
  for (const name of Object.keys(CONTRACT_SOURCES) as ContractName[]) {
    out[name] = readAbi(outDir, CONTRACT_SOURCES[name]);
  }
  return out;
}

export function abiHash(abi: unknown[]): string {
  return createHash('sha256').update(JSON.stringify(abi)).digest('hex');
}

export function abiVarName(name: string): string {
  // Handle consecutive uppercase letters followed by lowercase (e.g. CSModule -> csModule)
  if (/^[A-Z]{2,}[a-z]/.test(name)) {
    let i = 0;
    while (i < name.length) {
      const char = name[i];
      if (!char || !/[A-Z]/.test(char)) break;
      i++;
    }
    if (i > 1 && i < name.length) {
      const char = name[i];
      if (char && /[a-z]/.test(char)) {
        i--;
      }
    }
    return name.slice(0, i).toLowerCase() + name.slice(i) + 'Abi';
  }
  // For all-caps or simple names, just lowercase the first char (e.g. VEBO -> vEBO)
  return name.charAt(0).toLowerCase() + name.slice(1) + 'Abi';
}

export function renderAbiModule(varName: string, abi: unknown[]): string {
  return `// AUTO-GENERATED by scripts/refresh.ts — do not edit.\nexport const ${varName} = ${JSON.stringify(abi, null, 2)} as const;\n`;
}

export function renderAbiIndex(names: readonly string[]): string {
  const sorted = [...names].toSorted();
  const lines = sorted.map((n) => `export { ${abiVarName(n)} } from './${n}';`);
  return `// AUTO-GENERATED by scripts/refresh.ts — do not edit.\n${lines.join('\n')}\n`;
}

export function checkGitRef(headRef: string, deployRef: string, force: boolean): void {
  if (!force && headRef !== deployRef) {
    throw new Error(
      `Contracts HEAD ${headRef} != deployment git-ref ${deployRef}. ` +
        `Check out ${deployRef} in the contracts repo and rebuild, or pass --force.`,
    );
  }
}

export interface DeploySnapshot {
  'git-ref'?: string;
  [key: string]: unknown;
}

export function readDeploySnapshot(filePath: string): DeploySnapshot {
  if (!fs.existsSync(filePath)) {
    throw new Error(`Deploy snapshot not found at ${filePath}`);
  }
  return JSON.parse(fs.readFileSync(filePath, 'utf8')) as DeploySnapshot;
}

export interface SnapshotRef {
  chain: string;
  module: string;
  gitRef: string;
}

export interface Manifest {
  abiGitRef: string;
  abiHashes: Record<string, string>;
  snapshots: SnapshotRef[];
  generatedAt: string;
}

export function mergeManifest(
  prev: Manifest | null,
  next: {
    abiGitRef: string;
    abiHashes: Record<string, string>;
    snapshot: SnapshotRef;
    generatedAt: string;
  },
): Manifest {
  const snapshots = (prev?.snapshots ?? []).filter(
    (s) => !(s.chain === next.snapshot.chain && s.module === next.snapshot.module),
  );
  snapshots.push(next.snapshot);
  return {
    abiGitRef: next.abiGitRef,
    abiHashes: next.abiHashes,
    snapshots: snapshots.toSorted((a, b) =>
      `${a.chain}/${a.module}`.localeCompare(`${b.chain}/${b.module}`),
    ),
    generatedAt: next.generatedAt,
  };
}
